replicaCount: 1

image:
  repository: config-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8888

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

probes:
  liveness:
    path: /actuator/health
    initialDelaySeconds: 60
    periodSeconds: 15
  readiness:
    path: /actuator/health
    initialDelaySeconds: 30
    periodSeconds: 10
