apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue-db
  labels:
    app.kubernetes.io/name: catalogue-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: catalogue-db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: catalogue-db
    spec:
      containers:
        - name: postgres
          image: {{ .Values.database.image }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: catalogue-db-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: catalogue-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: catalogue-db-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-data
          readinessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
{{ toYaml .Values.database.resources | indent 12 }}
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: catalogue-db-pvc
